# Generated by Django 3.2 on 2021-04-24 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=3)),
                ('ready', models.BooleanField(default=False)),
                ('timeEnd', models.DateTimeField(blank=True, default=None, null=True)),
                ('playerTurn', models.IntegerField(blank=True, default=None, null=True)),
                ('chat_time', models.BooleanField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(default='This user does not have any bio yet', max_length=200)),
                ('picture', models.FileField(blank=True, upload_to='')),
                ('content_type', models.CharField(max_length=50)),
                ('following', models.ManyToManyField(default=None, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='profile_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(blank=True, default=None, null=True)),
                ('word', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('identity', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('is_dead', models.BooleanField(default=False)),
                ('player', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player', to='findspy.room')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('content', models.CharField(max_length=1000)),
                ('player', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='message', to='findspy.player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='findspy.room')),
            ],
        ),
    ]
