# Generated by Django 3.2 on 2021-04-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findspy', '0002_auto_20210411_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='room',
            name='current_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
