# Generated by Django 3.1.6 on 2021-04-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findspy', '0003_room_votetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
