# Generated by Django 3.1.6 on 2021-04-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findspy', '0004_auto_20210425_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_dead',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
