# Generated by Django 3.1.6 on 2021-04-26 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findspy', '0005_auto_20210425_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='player',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='message', to='findspy.player'),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='findspy.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='ready',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
