# Generated by Django 3.1.6 on 2021-04-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findspy', '0006_auto_20210425_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='chat_time',
        ),
        migrations.AddField(
            model_name='room',
            name='phase',
            field=models.CharField(blank=None, default=None, max_length=100, null=None),
        ),
    ]
