# Generated by Django 3.1.6 on 2021-04-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findspy', '0009_auto_20210426_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='msg',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='winner',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
